version: "3"
services:
    db:
        image: postgres:13
        restart: unless-stopped
        container_name: citiesdb
        ports:
            - "127.0.0.1:5432:5432"
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: restapicities
            POSTGRES_DB: cities
        volumes: 
            - ./postgres/pais.sql:/docker-entrypoint-initdb.d/1-pais.sql
            - ./postgres/estado.sql:/docker-entrypoint-initdb.d/2-estado.sql
            - ./postgres/cidade.sql:/docker-entrypoint-initdb.d/3-cidade.sql
            - ./postgres/extensao.sql:/docker-entrypoint-initdb.d/4-extensao.sql
        networks:
            - backend
    api:
        build: .
        restart: unless-stopped
        container_name: citiesapi
        ports:
            - "8080:8080"
        networks: 
            - backend
        depends_on:
            - db
networks: 
    backend:
        driver: bridge